version: '3.8'

services:
  webscraping_redis:
    image: "redis:alpine"
    container_name: webscraping_redis
    ports:
      - 6379:6379
    networks:
      - net_web

  ocr-app:
    build:
      context: ./web-scraper/
      target: app
    container_name: ocr-app
    command: bash -c "flask run --host=0.0.0.0 --port=5000"
    environment:
      - FLASK_APP=run
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./web-scraper:/app
    ports:
      - 5000:5000
    depends_on:
      - webscraping_redis
    networks:
      - net_web

  celery-worker:
    build: 
      context: ./web-scraper/
      target: worker
    container_name: celery-worker
    command: bash -c "celery -A run.celery worker -l info --pool=solo"
    depends_on:
      - webscraping_redis
    networks:
      - net_web
      - net_differ

  celery-beat:
    build: 
      context: ./web-scraper/
      target: beat
    container_name: celery-beat
    command: bash -c "celery -A run.celery beat -S redbeat.RedBeatScheduler --max-interval 30 --loglevel=info"
    environment:
      - CELERY_BROKER=redis://webscraping_redis:6379/0
      - CELERY_RESULT_BACKEND=redis://webscraping_redis:6379/0
      - CELERY_BEAT_SCHEDULE=redbeat.RedBeatScheduler
      - REDBEAT_REDIS_URL=redis://webscraping_redis:6379/0
    depends_on:
      - webscraping_redis
      - celery-worker
    networks:
      - net_web

  differ_redis:
    build:
      context: ./differ_module/differ_redis
    container_name: differ_redis
    ports:
      - 6381:6379
    networks:
      - net_differ

  differ_server:
    build:
      context: ./differ_module/differ_server
    container_name: differ_server
    ports:
      - 5010:5010
    depends_on:
      - differ_redis
    networks:
      - net_differ

  differ_worker:
    build:
      context: ./differ_module/differ_worker
    container_name: differ_worker
    depends_on:
      - differ_redis
      - differ_server
    networks:
      - net_differ
      - net_web

  postgres_api:
    build:
      context: ./differ_module/postgres_api
    container_name: postgres_api
    ports:
      - 5011:5011
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - net_db
      - net_differ

  db_server:
    build:
      context: ./differ_module/db_server
    container_name: db_server
    ports:
      - 5432:5432
    networks:
      - net_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  llm:
    build:
      context: ./llm
    container_name: llm
    ports:
      - 5020:5020
    networks:
      - net_web

  gui:
    build:
      context: ./gui/
    container_name: gui
    ports:
      - 3000:3000
    networks:
      - net_web

networks:
  net_web:
  net_differ:
  net_db:
