version: '3.8'
services:
  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "6379:6379"
    networks:
      - app-network
  ocr-app:
    build:
      context: .
    container_name: ocr-app
    command: bash -c "flask run --host=0.0.0.0 --port=5000"
    environment:
      - FLASK_APP=run
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network
  celery-worker:
    container_name: celery-worker
    build: .
    depends_on:
      - redis
    networks:
      - app-network
  celery-beat:
    container_name: celery-beat
    build: .
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BEAT_SCHEDULE=redbeat.RedBeatScheduler
      - REDBEAT_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
