version: '3.8'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - internal_net

  ocr-app:
    build:
      context: .
    container_name: ocr-app
    command: bash -c "flask run --host=0.0.0.0 --port=5000"
    environment:
      - FLASK_APP=run
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - internal_net
      - external_net

  celery-worker:
    container_name: celery-worker
    build: .
    command: bash -c "celery -A run.celery worker -l info --pool=solo"
    depends_on:
      - redis
    networks:
      - internal_net
      - external_net


  celery-beat:
    container_name: celery-beat
    build: .
    command: bash -c "celery -A run.celery beat -S redbeat.RedBeatScheduler --max-interval 30 --loglevel=info"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_BEAT_SCHEDULE=redbeat.RedBeatScheduler
      - REDBEAT_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery-worker
    networks:
      - internal_net
      - external_net
    
networks:
  internal_net:
    internal: true
  external_net:
    external: true
