name: CI

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: web-scraper
            target: app
          - path: web-scraper
            target: worker
          - path: web-scraper
            target: beat
          - path: llm
            target: worker
          - path: differ_module/postgres_api
          - path: gui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          if [ -n "${{ matrix.target }}" ]; then
            docker buildx build \
              --target ${{ matrix.target }} \
              -t test-${{ matrix.path }}-${{ matrix.target }} \
              ./${{ matrix.path }}
          else
            docker buildx build \
              -t test-${{ matrix.path }} \
              ./${{ matrix.path }}
          fi

      - name: Run and Log Container
        run: |
          set -e

          if [ "${{ matrix.path }}" == "web-scraper" ]; then
            docker run -d --name webscraper-${{ matrix.target }} test-${{ matrix.path }}-${{ matrix.target }}
            sleep 5
            docker logs webscraper-${{ matrix.target }}

          elif [ "${{ matrix.path }}" == "llm" ]; then
            docker run -d --name llm-${{ matrix.target }} test-${{ matrix.path }}-${{ matrix.target }}
            sleep 5
            docker logs llm-${{ matrix.target }}

          elif [ "${{ matrix.path }}" == "differ_module/postgres_api" ]; then
            docker run -d --name postgres_api_container -p 5011:5011 test-${{ matrix.path }}
            sleep 5
            docker logs postgres_api_container

          elif [ "${{ matrix.path }}" == "gui" ]; then
            docker run -d --name gui-container -p 3000:3000 test-${{ matrix.path }}
            sleep 5
            docker logs gui-container
          fi

      - name: Cleanup
        if: always()
        run: |
          docker ps -a -q | xargs -r docker stop
          docker ps -a -q | xargs -r docker rm
